### PR TITLE
Add MJN's XSTR Tool

### PR DESCRIPTION
**Pull request by wookieejedi**

### CODE REVIEW

**Review by JohnAFernandez — APPROVED** [review]

**Review by Shivansps — CHANGES_REQUESTED** [review]
Looking at the zip file the executable_path should be "Release/Etemenanki.exe"

**Comment by wookieejedi** [comment]
Good catch, just updated.

**Comment by MjnMixael** [comment]
I pushed 1.1.0 to fix the crashes I found last night. Might as well jump straight to that, but the zip file structure is idental.

**Comment by wookieejedi** [comment]
Perfect just updated it

**Comment by MjnMixael** [comment]
You missed a character in your link.

<https://github.com/MjnMixael/Etemenanki/releases/download/Version_1.0.0/Etemenanki_v1-1-0.zip>

<https://github.com/MjnMixael/Etemenanki/releases/download/**Version_1.1.0**/Etemenanki_v1-1-0.zip>

**Comment by wookieejedi** [comment]
Whoops just fixed, thanks!

**Pull request merged**
